-- Supabase Database Schema for Ebook Reader
-- Run this in your Supabase SQL Editor

-- Create books table
CREATE TABLE IF NOT EXISTS books (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  author TEXT,
  current_page INTEGER DEFAULT 0,
  last_chapter TEXT,
  total_pages INTEGER DEFAULT 0,
  last_read TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  file_url TEXT, -- Supabase Storage URL for EPUB file
  cover_url TEXT, -- Supabase Storage URL for cover image
  file_size BIGINT, -- File size in bytes
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE books ENABLE ROW LEVEL SECURITY;

-- Create policy: Users can only access their own books
CREATE POLICY "Users can manage their own books" ON books
  FOR ALL 
  USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

-- Create policy for authenticated users to insert their own books
CREATE POLICY "Users can insert their own books" ON books
  FOR INSERT 
  WITH CHECK (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_books_user_id ON books(user_id);
CREATE INDEX IF NOT EXISTS idx_books_last_read ON books(last_read DESC);
CREATE INDEX IF NOT EXISTS idx_books_title ON books(title);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_books_updated_at 
  BEFORE UPDATE ON books 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- Create storage bucket for book files
INSERT INTO storage.buckets (id, name, public) VALUES ('book-files', 'book-files', false);

-- Create storage bucket for cover images  
INSERT INTO storage.buckets (id, name, public) VALUES ('book-covers', 'book-covers', true);

-- Storage policies for book files
CREATE POLICY "Users can upload their own book files" ON storage.objects
  FOR INSERT 
  WITH CHECK (bucket_id = 'book-files' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can view their own book files" ON storage.objects
  FOR SELECT 
  USING (bucket_id = 'book-files' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can delete their own book files" ON storage.objects
  FOR DELETE 
  USING (bucket_id = 'book-files' AND auth.uid()::text = (storage.foldername(name))[1]);

-- Storage policies for cover images (public readable)
CREATE POLICY "Users can upload their own cover images" ON storage.objects
  FOR INSERT 
  WITH CHECK (bucket_id = 'book-covers' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Anyone can view cover images" ON storage.objects
  FOR SELECT 
  USING (bucket_id = 'book-covers');

CREATE POLICY "Users can delete their own cover images" ON storage.objects
  FOR DELETE 
  USING (bucket_id = 'book-covers' AND auth.uid()::text = (storage.foldername(name))[1]); 

-- === TTS USAGE TRACKING ===

-- Monthly quota/usage per user
CREATE TABLE IF NOT EXISTS tts_quota_monthly (
  user_id uuid NOT NULL,
  month_start date NOT NULL,
  used_seconds integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, month_start)
);

ALTER TABLE tts_quota_monthly ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can read own monthly tts usage" ON tts_quota_monthly
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "User can upsert own monthly tts usage" ON tts_quota_monthly
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "User can update own monthly tts usage" ON tts_quota_monthly
  FOR UPDATE USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_tts_quota_monthly_user_month ON tts_quota_monthly(user_id, month_start DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_tts_quota_monthly_updated_at ON tts_quota_monthly;
CREATE TRIGGER trg_tts_quota_monthly_updated_at
  BEFORE UPDATE ON tts_quota_monthly
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Optional: raw usage event log
CREATE TABLE IF NOT EXISTS tts_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid NOT NULL,
  seconds integer NOT NULL,
  source text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE tts_usage_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can insert own tts usage events" ON tts_usage_events
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "User can read own tts usage events" ON tts_usage_events
  FOR SELECT USING (user_id = auth.uid());

-- Per-source monthly usage (e.g., reader vs full-cast)
CREATE TABLE IF NOT EXISTS tts_quota_monthly_by_source (
  user_id uuid NOT NULL,
  month_start date NOT NULL,
  source text NOT NULL,
  used_seconds integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, month_start, source)
);

ALTER TABLE tts_quota_monthly_by_source ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can read own monthly tts usage by source" ON tts_quota_monthly_by_source
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "User can upsert own monthly tts usage by source" ON tts_quota_monthly_by_source
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "User can update own monthly tts usage by source" ON tts_quota_monthly_by_source
  FOR UPDATE USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_tts_quota_monthly_by_source_user_month
  ON tts_quota_monthly_by_source(user_id, month_start DESC, source);

-- Create the trigger only if it doesn't already exist (no DROP)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    WHERE t.tgname = 'trg_tts_quota_monthly_by_source_updated_at'
      AND c.relname = 'tts_quota_monthly_by_source'
  ) THEN
    CREATE TRIGGER trg_tts_quota_monthly_by_source_updated_at
      BEFORE UPDATE ON tts_quota_monthly_by_source
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;

-- RPC to fetch caller's Full Cast usage by email (safe for client use)
CREATE OR REPLACE FUNCTION get_full_cast_usage_by_email(
  p_email text
)
RETURNS TABLE (
  used_seconds integer,
  month_start date
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_email text;
  v_claim_email text;
BEGIN
  v_email := coalesce(p_email, '');
  v_claim_email := coalesce(current_setting('request.jwt.claims', true)::json->>'email', '');

  -- Ensure caller can only request their own email
  IF v_claim_email IS NULL OR v_claim_email = '' OR v_claim_email <> v_email THEN
    RAISE EXCEPTION 'Unauthorized for this email';
  END IF;

  SELECT id INTO v_user_id FROM auth.users WHERE email = v_email;
  IF v_user_id IS NULL THEN
    RETURN QUERY SELECT 0::int AS used_seconds, date_trunc('month', now())::date AS month_start;
    RETURN;
  END IF;

  RETURN QUERY
  SELECT q.used_seconds, q.month_start
  FROM tts_quota_monthly_by_source q
  WHERE q.user_id = v_user_id AND q.source = 'full-cast'
  ORDER BY q.month_start DESC
  LIMIT 1;
END;
$$;

-- RPC to increment usage safely under RLS
CREATE OR REPLACE FUNCTION increment_tts_usage(
  p_user_id uuid,
  p_seconds integer,
  p_source text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_user_id uuid;
  v_month_start date;
BEGIN
  IF p_seconds IS NULL OR p_seconds <= 0 THEN
    RETURN;
  END IF;

  v_user_id := COALESCE(p_user_id, auth.uid());
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'increment_tts_usage: user id is required';
  END IF;

  v_month_start := date_trunc('month', now())::date;

  -- Upsert monthly bucket
  INSERT INTO tts_quota_monthly (user_id, month_start, used_seconds)
  VALUES (v_user_id, v_month_start, p_seconds)
  ON CONFLICT (user_id, month_start)
  DO UPDATE SET used_seconds = tts_quota_monthly.used_seconds + EXCLUDED.used_seconds,
                updated_at = now();

  -- Upsert per-source monthly bucket
  INSERT INTO tts_quota_monthly_by_source (user_id, month_start, source, used_seconds)
  VALUES (v_user_id, v_month_start, COALESCE(NULLIF(p_source, ''), 'unknown'), p_seconds)
  ON CONFLICT (user_id, month_start, source)
  DO UPDATE SET used_seconds = tts_quota_monthly_by_source.used_seconds + EXCLUDED.used_seconds,
                updated_at = now();

  -- Append raw event (optional)
  INSERT INTO tts_usage_events (user_id, seconds, source)
  VALUES (v_user_id, p_seconds, p_source);
END;
$$;
