-- Supabase Database Schema for Ebook Reader
-- Run this in your Supabase SQL Editor

-- Create books table
CREATE TABLE IF NOT EXISTS books (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  author TEXT,
  current_page INTEGER DEFAULT 0,
  last_chapter TEXT,
  total_pages INTEGER DEFAULT 0,
  last_read TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  file_url TEXT, -- Supabase Storage URL for EPUB file
  cover_url TEXT, -- Supabase Storage URL for cover image
  file_size BIGINT, -- File size in bytes
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE books ENABLE ROW LEVEL SECURITY;

-- Create policy: Users can only access their own books
CREATE POLICY "Users can manage their own books" ON books
  FOR ALL 
  USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

-- Create policy for authenticated users to insert their own books
CREATE POLICY "Users can insert their own books" ON books
  FOR INSERT 
  WITH CHECK (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_books_user_id ON books(user_id);
CREATE INDEX IF NOT EXISTS idx_books_last_read ON books(last_read DESC);
CREATE INDEX IF NOT EXISTS idx_books_title ON books(title);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_books_updated_at 
  BEFORE UPDATE ON books 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- Create storage bucket for book files
INSERT INTO storage.buckets (id, name, public) VALUES ('book-files', 'book-files', false);

-- Create storage bucket for cover images  
INSERT INTO storage.buckets (id, name, public) VALUES ('book-covers', 'book-covers', true);

-- Storage policies for book files
CREATE POLICY "Users can upload their own book files" ON storage.objects
  FOR INSERT 
  WITH CHECK (bucket_id = 'book-files' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can view their own book files" ON storage.objects
  FOR SELECT 
  USING (bucket_id = 'book-files' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can delete their own book files" ON storage.objects
  FOR DELETE 
  USING (bucket_id = 'book-files' AND auth.uid()::text = (storage.foldername(name))[1]);

-- Storage policies for cover images (public readable)
CREATE POLICY "Users can upload their own cover images" ON storage.objects
  FOR INSERT 
  WITH CHECK (bucket_id = 'book-covers' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Anyone can view cover images" ON storage.objects
  FOR SELECT 
  USING (bucket_id = 'book-covers');

CREATE POLICY "Users can delete their own cover images" ON storage.objects
  FOR DELETE 
  USING (bucket_id = 'book-covers' AND auth.uid()::text = (storage.foldername(name))[1]); 

-- === TTS USAGE TRACKING ===

-- Monthly quota/usage per user
CREATE TABLE IF NOT EXISTS tts_quota_monthly (
  user_id uuid NOT NULL,
  month_start date NOT NULL,
  used_seconds integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, month_start)
);

ALTER TABLE tts_quota_monthly ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can read own monthly tts usage" ON tts_quota_monthly
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "User can upsert own monthly tts usage" ON tts_quota_monthly
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "User can update own monthly tts usage" ON tts_quota_monthly
  FOR UPDATE USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_tts_quota_monthly_user_month ON tts_quota_monthly(user_id, month_start DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_tts_quota_monthly_updated_at ON tts_quota_monthly;
CREATE TRIGGER trg_tts_quota_monthly_updated_at
  BEFORE UPDATE ON tts_quota_monthly
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Optional: raw usage event log with idempotency support
CREATE TABLE IF NOT EXISTS tts_usage_events (
  id bigint generated by default as identity primary key,
  event_id text UNIQUE, -- For idempotency: unique constraint prevents duplicate processing
  user_id uuid NOT NULL,
  seconds integer NOT NULL,
  source text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Add index on event_id for fast duplicate checks
CREATE INDEX IF NOT EXISTS idx_tts_usage_events_event_id ON tts_usage_events(event_id) WHERE event_id IS NOT NULL;

ALTER TABLE tts_usage_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can insert own tts usage events" ON tts_usage_events
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "User can read own tts usage events" ON tts_usage_events
  FOR SELECT USING (user_id = auth.uid());

-- Per-source monthly usage (e.g., reader vs full-cast)
CREATE TABLE IF NOT EXISTS tts_quota_monthly_by_source (
  user_id uuid NOT NULL,
  month_start date NOT NULL,
  source text NOT NULL,
  used_seconds integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, month_start, source)
);

ALTER TABLE tts_quota_monthly_by_source ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can read own monthly tts usage by source" ON tts_quota_monthly_by_source
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "User can upsert own monthly tts usage by source" ON tts_quota_monthly_by_source
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "User can update own monthly tts usage by source" ON tts_quota_monthly_by_source
  FOR UPDATE USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_tts_quota_monthly_by_source_user_month
  ON tts_quota_monthly_by_source(user_id, month_start DESC, source);

-- Create the trigger only if it doesn't already exist (no DROP)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    WHERE t.tgname = 'trg_tts_quota_monthly_by_source_updated_at'
      AND c.relname = 'tts_quota_monthly_by_source'
  ) THEN
    CREATE TRIGGER trg_tts_quota_monthly_by_source_updated_at
      BEFORE UPDATE ON tts_quota_monthly_by_source
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;

-- RPC to fetch caller's Full Cast usage by email (safe for client use)
CREATE OR REPLACE FUNCTION get_full_cast_usage_by_email(
  p_email text
)
RETURNS TABLE (
  used_seconds integer,
  month_start date
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_email text;
  v_claim_email text;
BEGIN
  v_email := coalesce(p_email, '');
  v_claim_email := coalesce(current_setting('request.jwt.claims', true)::json->>'email', '');

  -- Ensure caller can only request their own email
  IF v_claim_email IS NULL OR v_claim_email = '' OR v_claim_email <> v_email THEN
    RAISE EXCEPTION 'Unauthorized for this email';
  END IF;

  SELECT id INTO v_user_id FROM auth.users WHERE email = v_email;
  IF v_user_id IS NULL THEN
    RETURN QUERY SELECT 0::int AS used_seconds, date_trunc('month', now())::date AS month_start;
    RETURN;
  END IF;

  RETURN QUERY
  SELECT q.used_seconds, q.month_start
  FROM tts_quota_monthly_by_source q
  WHERE q.user_id = v_user_id AND q.source = 'full-cast'
  ORDER BY q.month_start DESC
  LIMIT 1;
END;
$$;

-- RPC to increment usage safely under RLS with idempotency support
CREATE OR REPLACE FUNCTION increment_tts_usage(
  p_user_id uuid,
  p_seconds integer,
  p_source text DEFAULT NULL,
  p_event_id text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_month_start date;
  v_event_inserted boolean := false;
BEGIN
  -- Validate inputs
  IF p_seconds IS NULL OR p_seconds <= 0 THEN
    RETURN;
  END IF;

  v_user_id := COALESCE(p_user_id, auth.uid());
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'increment_tts_usage: user id is required';
  END IF;

  v_month_start := date_trunc('month', now())::date;

  -- Insert event with idempotency check (if event_id provided)
  -- This prevents double-counting if the same event is processed twice
  IF p_event_id IS NOT NULL AND p_event_id != '' THEN
    BEGIN
      INSERT INTO tts_usage_events (event_id, user_id, seconds, source)
      VALUES (p_event_id, v_user_id, p_seconds, p_source)
      ON CONFLICT (event_id) DO NOTHING
      RETURNING true INTO v_event_inserted;
      
      -- If event already exists (idempotency hit), skip quota updates
      IF NOT v_event_inserted THEN
        -- Event already processed, exit early to prevent double-counting
        RETURN;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        -- Log error but continue with quota updates
        RAISE WARNING 'Failed to insert event with id %: %', p_event_id, SQLERRM;
    END;
  ELSE
    -- No event_id provided, insert event without idempotency check
    BEGIN
      INSERT INTO tts_usage_events (user_id, seconds, source)
      VALUES (v_user_id, p_seconds, p_source);
      v_event_inserted := true;
    EXCEPTION
      WHEN OTHERS THEN
        RAISE WARNING 'Failed to insert event: %', SQLERRM;
        -- Continue with quota updates even if event insert fails
    END;
  END IF;

  -- Upsert monthly bucket (only if event was successfully inserted or no event_id provided)
  IF v_event_inserted OR p_event_id IS NULL THEN
    INSERT INTO tts_quota_monthly (user_id, month_start, used_seconds)
    VALUES (v_user_id, v_month_start, p_seconds)
    ON CONFLICT (user_id, month_start)
    DO UPDATE SET used_seconds = tts_quota_monthly.used_seconds + EXCLUDED.used_seconds,
                  updated_at = now();
  END IF;

  -- Upsert per-source monthly bucket (only if event was successfully inserted or no event_id provided)
  IF v_event_inserted OR p_event_id IS NULL THEN
    INSERT INTO tts_quota_monthly_by_source (user_id, month_start, source, used_seconds)
    VALUES (v_user_id, v_month_start, COALESCE(NULLIF(p_source, ''), 'unknown'), p_seconds)
    ON CONFLICT (user_id, month_start, source)
    DO UPDATE SET used_seconds = tts_quota_monthly_by_source.used_seconds + EXCLUDED.used_seconds,
                  updated_at = now();
  END IF;
END;
$$;

-- === ANONYMOUS USER TRACKING ===

-- Anonymous sessions table
CREATE TABLE IF NOT EXISTS anonymous_tts_sessions (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now(),
  last_active_at timestamptz DEFAULT now(),
  user_agent text,
  ip_address text, -- Optional, for analytics
  converted_to_user_id uuid REFERENCES auth.users(id), -- Track conversions
  conversion_date timestamptz,
  total_tts_seconds integer DEFAULT 0,
  total_full_cast_seconds integer DEFAULT 0,
  
  -- Index for performance
  CONSTRAINT session_id_format CHECK (session_id ~ '^anon_[0-9]+_[a-z0-9]+$')
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_anonymous_sessions_session_id ON anonymous_tts_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_anonymous_sessions_converted ON anonymous_tts_sessions(converted_to_user_id) WHERE converted_to_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_anonymous_sessions_last_active ON anonymous_tts_sessions(last_active_at);

-- Anonymous usage table (detailed tracking)
CREATE TABLE IF NOT EXISTS anonymous_tts_usage (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id text NOT NULL REFERENCES anonymous_tts_sessions(session_id) ON DELETE CASCADE,
  month_start date NOT NULL,
  source text NOT NULL, -- 'reader' or 'full-cast'
  used_seconds integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  
  -- Unique constraint: one row per session, month, and source
  UNIQUE(session_id, month_start, source)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_anonymous_usage_session ON anonymous_tts_usage(session_id);
CREATE INDEX IF NOT EXISTS idx_anonymous_usage_month ON anonymous_tts_usage(month_start);
CREATE INDEX IF NOT EXISTS idx_anonymous_usage_source ON anonymous_tts_usage(source);

-- RLS policies for anonymous tables
ALTER TABLE anonymous_tts_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE anonymous_tts_usage ENABLE ROW LEVEL SECURITY;

-- Anyone can insert (no auth required)
CREATE POLICY "Allow anonymous session creation" 
  ON anonymous_tts_sessions FOR INSERT 
  WITH CHECK (true);

-- Anyone can update their own session (by session_id match)
CREATE POLICY "Allow anonymous session update" 
  ON anonymous_tts_sessions FOR UPDATE 
  USING (true);

-- Anyone can insert usage
CREATE POLICY "Allow anonymous usage insert" 
  ON anonymous_tts_usage FOR INSERT 
  WITH CHECK (true);

-- Anyone can update usage
CREATE POLICY "Allow anonymous usage update" 
  ON anonymous_tts_usage FOR UPDATE 
  USING (true);

-- Only authenticated users can read (for privacy)
CREATE POLICY "Allow authenticated read of anonymous sessions" 
  ON anonymous_tts_sessions FOR SELECT 
  USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Allow authenticated read of anonymous usage" 
  ON anonymous_tts_usage FOR SELECT 
  USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

-- Add updated_at trigger for anonymous_tts_usage
CREATE TRIGGER trg_anonymous_tts_usage_updated_at
  BEFORE UPDATE ON anonymous_tts_usage
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- RPC to record anonymous TTS usage
CREATE OR REPLACE FUNCTION record_anonymous_tts_usage(
  p_session_id text,
  p_seconds integer,
  p_source text DEFAULT 'reader',
  p_user_agent text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  v_month_start date;
  v_session_exists boolean;
  v_total_seconds integer;
BEGIN
  -- Validate inputs
  IF p_session_id IS NULL OR p_session_id = '' THEN
    RAISE EXCEPTION 'session_id is required';
  END IF;
  
  IF p_seconds IS NULL OR p_seconds <= 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invalid seconds value');
  END IF;
  
  v_month_start := date_trunc('month', now())::date;
  
  -- Check if session exists
  SELECT EXISTS(
    SELECT 1 FROM anonymous_tts_sessions WHERE session_id = p_session_id
  ) INTO v_session_exists;
  
  -- Create session if it doesn't exist
  IF NOT v_session_exists THEN
    INSERT INTO anonymous_tts_sessions (
      session_id, 
      user_agent,
      total_tts_seconds,
      total_full_cast_seconds
    ) VALUES (
      p_session_id,
      p_user_agent,
      CASE WHEN p_source = 'reader' THEN p_seconds ELSE 0 END,
      CASE WHEN p_source = 'full-cast' THEN p_seconds ELSE 0 END
    );
  ELSE
    -- Update session totals and last_active
    UPDATE anonymous_tts_sessions
    SET 
      last_active_at = now(),
      total_tts_seconds = total_tts_seconds + CASE WHEN p_source = 'reader' THEN p_seconds ELSE 0 END,
      total_full_cast_seconds = total_full_cast_seconds + CASE WHEN p_source = 'full-cast' THEN p_seconds ELSE 0 END
    WHERE session_id = p_session_id;
  END IF;
  
  -- Upsert monthly usage by source
  INSERT INTO anonymous_tts_usage (
    session_id,
    month_start,
    source,
    used_seconds
  ) VALUES (
    p_session_id,
    v_month_start,
    COALESCE(NULLIF(p_source, ''), 'reader'),
    p_seconds
  )
  ON CONFLICT (session_id, month_start, source)
  DO UPDATE SET 
    used_seconds = anonymous_tts_usage.used_seconds + EXCLUDED.used_seconds,
    updated_at = now();
  
  -- Get current total for this session
  SELECT COALESCE(SUM(used_seconds), 0)
  INTO v_total_seconds
  FROM anonymous_tts_usage
  WHERE session_id = p_session_id
    AND month_start = v_month_start;
  
  RETURN jsonb_build_object(
    'success', true,
    'session_id', p_session_id,
    'total_seconds_this_month', v_total_seconds,
    'total_minutes_this_month', ROUND(v_total_seconds / 60.0, 2)
  );
END;
$$;

-- RPC to convert anonymous session to user
CREATE OR REPLACE FUNCTION convert_anonymous_to_user(
  p_session_id text,
  p_user_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  v_tts_seconds integer;
  v_full_cast_seconds integer;
  v_month_start date;
BEGIN
  v_month_start := date_trunc('month', now())::date;
  
  -- Get anonymous totals
  SELECT 
    COALESCE(total_tts_seconds, 0),
    COALESCE(total_full_cast_seconds, 0)
  INTO v_tts_seconds, v_full_cast_seconds
  FROM anonymous_tts_sessions
  WHERE session_id = p_session_id;
  
  IF v_tts_seconds IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Session not found');
  END IF;
  
  -- Mark session as converted
  UPDATE anonymous_tts_sessions
  SET 
    converted_to_user_id = p_user_id,
    conversion_date = now()
  WHERE session_id = p_session_id;
  
  -- Transfer usage to authenticated user tables
  -- Only transfer current month's usage
  INSERT INTO tts_quota_monthly (user_id, month_start, used_seconds)
  VALUES (p_user_id, v_month_start, v_tts_seconds + v_full_cast_seconds)
  ON CONFLICT (user_id, month_start)
  DO UPDATE SET 
    used_seconds = tts_quota_monthly.used_seconds + EXCLUDED.used_seconds;
  
  -- Transfer by source
  IF v_tts_seconds > 0 THEN
    INSERT INTO tts_quota_monthly_by_source (user_id, month_start, source, used_seconds)
    VALUES (p_user_id, v_month_start, 'reader', v_tts_seconds)
    ON CONFLICT (user_id, month_start, source)
    DO UPDATE SET 
      used_seconds = tts_quota_monthly_by_source.used_seconds + EXCLUDED.used_seconds;
  END IF;
  
  IF v_full_cast_seconds > 0 THEN
    INSERT INTO tts_quota_monthly_by_source (user_id, month_start, source, used_seconds)
    VALUES (p_user_id, v_month_start, 'full-cast', v_full_cast_seconds)
    ON CONFLICT (user_id, month_start, source)
    DO UPDATE SET 
      used_seconds = tts_quota_monthly_by_source.used_seconds + EXCLUDED.used_seconds;
  END IF;
  
  RETURN jsonb_build_object(
    'success', true,
    'transferred_tts_seconds', v_tts_seconds,
    'transferred_full_cast_seconds', v_full_cast_seconds,
    'user_id', p_user_id
  );
END;
$$;

-- RPC to get anonymous user's current usage
CREATE OR REPLACE FUNCTION get_anonymous_usage(
  p_session_id text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_month_start date;
  v_total_seconds integer;
  v_tts_seconds integer;
  v_full_cast_seconds integer;
BEGIN
  v_month_start := date_trunc('month', now())::date;
  
  -- Get total usage for this session this month
  SELECT 
    COALESCE(SUM(used_seconds), 0)
  INTO v_total_seconds
  FROM anonymous_tts_usage
  WHERE session_id = p_session_id
    AND month_start = v_month_start;
  
  -- Get breakdown by source
  SELECT 
    COALESCE(SUM(CASE WHEN source = 'reader' THEN used_seconds ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN source = 'full-cast' THEN used_seconds ELSE 0 END), 0)
  INTO v_tts_seconds, v_full_cast_seconds
  FROM anonymous_tts_usage
  WHERE session_id = p_session_id
    AND month_start = v_month_start;
  
  RETURN jsonb_build_object(
    'session_id', p_session_id,
    'total_seconds', v_total_seconds,
    'total_minutes', ROUND(v_total_seconds / 60.0, 2),
    'tts_seconds', v_tts_seconds,
    'full_cast_seconds', v_full_cast_seconds,
    'month_start', v_month_start
  );
END;
$$;