-- Supabase Database Schema for Ebook Reader
-- Run this in your Supabase SQL Editor

-- Create books table
CREATE TABLE IF NOT EXISTS books (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  author TEXT,
  current_page INTEGER DEFAULT 0,
  last_chapter TEXT,
  total_pages INTEGER DEFAULT 0,
  last_read TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  file_url TEXT, -- Supabase Storage URL for EPUB file
  cover_url TEXT, -- Supabase Storage URL for cover image
  file_size BIGINT, -- File size in bytes
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE books ENABLE ROW LEVEL SECURITY;

-- Create policy: Users can only access their own books
CREATE POLICY "Users can manage their own books" ON books
  FOR ALL 
  USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

-- Create policy for authenticated users to insert their own books
CREATE POLICY "Users can insert their own books" ON books
  FOR INSERT 
  WITH CHECK (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_books_user_id ON books(user_id);
CREATE INDEX IF NOT EXISTS idx_books_last_read ON books(last_read DESC);
CREATE INDEX IF NOT EXISTS idx_books_title ON books(title);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_books_updated_at 
  BEFORE UPDATE ON books 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- Create storage bucket for book files
INSERT INTO storage.buckets (id, name, public) VALUES ('book-files', 'book-files', false);

-- Create storage bucket for cover images  
INSERT INTO storage.buckets (id, name, public) VALUES ('book-covers', 'book-covers', true);

-- Storage policies for book files
CREATE POLICY "Users can upload their own book files" ON storage.objects
  FOR INSERT 
  WITH CHECK (bucket_id = 'book-files' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can view their own book files" ON storage.objects
  FOR SELECT 
  USING (bucket_id = 'book-files' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can delete their own book files" ON storage.objects
  FOR DELETE 
  USING (bucket_id = 'book-files' AND auth.uid()::text = (storage.foldername(name))[1]);

-- Storage policies for cover images (public readable)
CREATE POLICY "Users can upload their own cover images" ON storage.objects
  FOR INSERT 
  WITH CHECK (bucket_id = 'book-covers' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Anyone can view cover images" ON storage.objects
  FOR SELECT 
  USING (bucket_id = 'book-covers');

CREATE POLICY "Users can delete their own cover images" ON storage.objects
  FOR DELETE 
  USING (bucket_id = 'book-covers' AND auth.uid()::text = (storage.foldername(name))[1]); 

-- === TTS USAGE TRACKING ===

-- Monthly quota/usage per user
CREATE TABLE IF NOT EXISTS tts_quota_monthly (
  user_id uuid NOT NULL,
  month_start date NOT NULL,
  used_seconds integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, month_start)
);

ALTER TABLE tts_quota_monthly ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can read own monthly tts usage" ON tts_quota_monthly
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "User can upsert own monthly tts usage" ON tts_quota_monthly
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "User can update own monthly tts usage" ON tts_quota_monthly
  FOR UPDATE USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_tts_quota_monthly_user_month ON tts_quota_monthly(user_id, month_start DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_tts_quota_monthly_updated_at ON tts_quota_monthly;
CREATE TRIGGER trg_tts_quota_monthly_updated_at
  BEFORE UPDATE ON tts_quota_monthly
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Optional: raw usage event log with idempotency support
CREATE TABLE IF NOT EXISTS tts_usage_events (
  id bigint generated by default as identity primary key,
  event_id text UNIQUE, -- For idempotency: unique constraint prevents duplicate processing
  user_id uuid NOT NULL,
  seconds integer NOT NULL,
  source text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Add index on event_id for fast duplicate checks
CREATE INDEX IF NOT EXISTS idx_tts_usage_events_event_id ON tts_usage_events(event_id) WHERE event_id IS NOT NULL;

ALTER TABLE tts_usage_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can insert own tts usage events" ON tts_usage_events
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "User can read own tts usage events" ON tts_usage_events
  FOR SELECT USING (user_id = auth.uid());

-- Per-source monthly usage (e.g., reader vs full-cast)
CREATE TABLE IF NOT EXISTS tts_quota_monthly_by_source (
  user_id uuid NOT NULL,
  month_start date NOT NULL,
  source text NOT NULL,
  used_seconds integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, month_start, source)
);

ALTER TABLE tts_quota_monthly_by_source ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can read own monthly tts usage by source" ON tts_quota_monthly_by_source
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "User can upsert own monthly tts usage by source" ON tts_quota_monthly_by_source
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "User can update own monthly tts usage by source" ON tts_quota_monthly_by_source
  FOR UPDATE USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_tts_quota_monthly_by_source_user_month
  ON tts_quota_monthly_by_source(user_id, month_start DESC, source);

-- Create the trigger only if it doesn't already exist (no DROP)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    WHERE t.tgname = 'trg_tts_quota_monthly_by_source_updated_at'
      AND c.relname = 'tts_quota_monthly_by_source'
  ) THEN
    CREATE TRIGGER trg_tts_quota_monthly_by_source_updated_at
      BEFORE UPDATE ON tts_quota_monthly_by_source
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;

-- RPC to fetch caller's Full Cast usage by email (safe for client use)
CREATE OR REPLACE FUNCTION get_full_cast_usage_by_email(
  p_email text
)
RETURNS TABLE (
  used_seconds integer,
  month_start date
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_email text;
  v_claim_email text;
BEGIN
  v_email := coalesce(p_email, '');
  v_claim_email := coalesce(current_setting('request.jwt.claims', true)::json->>'email', '');

  -- Ensure caller can only request their own email
  IF v_claim_email IS NULL OR v_claim_email = '' OR v_claim_email <> v_email THEN
    RAISE EXCEPTION 'Unauthorized for this email';
  END IF;

  SELECT id INTO v_user_id FROM auth.users WHERE email = v_email;
  IF v_user_id IS NULL THEN
    RETURN QUERY SELECT 0::int AS used_seconds, date_trunc('month', now())::date AS month_start;
    RETURN;
  END IF;

  RETURN QUERY
  SELECT q.used_seconds, q.month_start
  FROM tts_quota_monthly_by_source q
  WHERE q.user_id = v_user_id AND q.source = 'full-cast'
  ORDER BY q.month_start DESC
  LIMIT 1;
END;
$$;

-- RPC to increment usage safely under RLS with idempotency support
CREATE OR REPLACE FUNCTION increment_tts_usage(
  p_user_id uuid,
  p_seconds integer,
  p_source text DEFAULT NULL,
  p_event_id text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_month_start date;
  v_event_inserted boolean := false;
BEGIN
  -- Validate inputs
  IF p_seconds IS NULL OR p_seconds <= 0 THEN
    RETURN;
  END IF;

  v_user_id := COALESCE(p_user_id, auth.uid());
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'increment_tts_usage: user id is required';
  END IF;

  v_month_start := date_trunc('month', now())::date;

  -- Insert event with idempotency check (if event_id provided)
  -- This prevents double-counting if the same event is processed twice
  IF p_event_id IS NOT NULL AND p_event_id != '' THEN
    BEGIN
      INSERT INTO tts_usage_events (event_id, user_id, seconds, source)
      VALUES (p_event_id, v_user_id, p_seconds, p_source)
      ON CONFLICT (event_id) DO NOTHING
      RETURNING true INTO v_event_inserted;
      
      -- If event already exists (idempotency hit), skip quota updates
      IF NOT v_event_inserted THEN
        -- Event already processed, exit early to prevent double-counting
        RETURN;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        -- Log error but continue with quota updates
        RAISE WARNING 'Failed to insert event with id %: %', p_event_id, SQLERRM;
    END;
  ELSE
    -- No event_id provided, insert event without idempotency check
    BEGIN
      INSERT INTO tts_usage_events (user_id, seconds, source)
      VALUES (v_user_id, p_seconds, p_source);
      v_event_inserted := true;
    EXCEPTION
      WHEN OTHERS THEN
        RAISE WARNING 'Failed to insert event: %', SQLERRM;
        -- Continue with quota updates even if event insert fails
    END;
  END IF;

  -- Upsert monthly bucket (only if event was successfully inserted or no event_id provided)
  IF v_event_inserted OR p_event_id IS NULL THEN
    INSERT INTO tts_quota_monthly (user_id, month_start, used_seconds)
    VALUES (v_user_id, v_month_start, p_seconds)
    ON CONFLICT (user_id, month_start)
    DO UPDATE SET used_seconds = tts_quota_monthly.used_seconds + EXCLUDED.used_seconds,
                  updated_at = now();
  END IF;

  -- Upsert per-source monthly bucket (only if event was successfully inserted or no event_id provided)
  IF v_event_inserted OR p_event_id IS NULL THEN
    INSERT INTO tts_quota_monthly_by_source (user_id, month_start, source, used_seconds)
    VALUES (v_user_id, v_month_start, COALESCE(NULLIF(p_source, ''), 'unknown'), p_seconds)
    ON CONFLICT (user_id, month_start, source)
    DO UPDATE SET used_seconds = tts_quota_monthly_by_source.used_seconds + EXCLUDED.used_seconds,
                  updated_at = now();
  END IF;
END;
$$;

-- === ANONYMOUS USER TRACKING ===

-- Anonymous sessions table
CREATE TABLE IF NOT EXISTS anonymous_tts_sessions (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now(),
  last_active_at timestamptz DEFAULT now(),
  user_agent text,
  ip_address text, -- Optional, for analytics
  converted_to_user_id uuid REFERENCES auth.users(id), -- Track conversions
  conversion_date timestamptz,
  total_tts_seconds integer DEFAULT 0,
  total_full_cast_seconds integer DEFAULT 0,
  
  -- Index for performance
  CONSTRAINT session_id_format CHECK (session_id ~ '^anon_[0-9]+_[a-z0-9]+$')
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_anonymous_sessions_session_id ON anonymous_tts_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_anonymous_sessions_converted ON anonymous_tts_sessions(converted_to_user_id) WHERE converted_to_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_anonymous_sessions_last_active ON anonymous_tts_sessions(last_active_at);

-- Anonymous usage table (detailed tracking)
CREATE TABLE IF NOT EXISTS anonymous_tts_usage (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id text NOT NULL REFERENCES anonymous_tts_sessions(session_id) ON DELETE CASCADE,
  month_start date NOT NULL,
  source text NOT NULL, -- 'reader' or 'full-cast'
  used_seconds integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  
  -- Unique constraint: one row per session, month, and source
  UNIQUE(session_id, month_start, source)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_anonymous_usage_session ON anonymous_tts_usage(session_id);
CREATE INDEX IF NOT EXISTS idx_anonymous_usage_month ON anonymous_tts_usage(month_start);
CREATE INDEX IF NOT EXISTS idx_anonymous_usage_source ON anonymous_tts_usage(source);

-- RLS policies for anonymous tables
ALTER TABLE anonymous_tts_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE anonymous_tts_usage ENABLE ROW LEVEL SECURITY;

-- Anyone can insert (no auth required)
CREATE POLICY "Allow anonymous session creation" 
  ON anonymous_tts_sessions FOR INSERT 
  WITH CHECK (true);

-- Anyone can update their own session (by session_id match)
CREATE POLICY "Allow anonymous session update" 
  ON anonymous_tts_sessions FOR UPDATE 
  USING (true);

-- Anyone can insert usage
CREATE POLICY "Allow anonymous usage insert" 
  ON anonymous_tts_usage FOR INSERT 
  WITH CHECK (true);

-- Anyone can update usage
CREATE POLICY "Allow anonymous usage update" 
  ON anonymous_tts_usage FOR UPDATE 
  USING (true);

-- Only authenticated users can read (for privacy)
CREATE POLICY "Allow authenticated read of anonymous sessions" 
  ON anonymous_tts_sessions FOR SELECT 
  USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Allow authenticated read of anonymous usage" 
  ON anonymous_tts_usage FOR SELECT 
  USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

-- Add updated_at trigger for anonymous_tts_usage
CREATE TRIGGER trg_anonymous_tts_usage_updated_at
  BEFORE UPDATE ON anonymous_tts_usage
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- RPC to record anonymous TTS usage
CREATE OR REPLACE FUNCTION record_anonymous_tts_usage(
  p_session_id text,
  p_seconds integer,
  p_source text DEFAULT 'reader',
  p_user_agent text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  v_month_start date;
  v_session_exists boolean;
  v_total_seconds integer;
BEGIN
  -- Validate inputs
  IF p_session_id IS NULL OR p_session_id = '' THEN
    RAISE EXCEPTION 'session_id is required';
  END IF;
  
  IF p_seconds IS NULL OR p_seconds <= 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invalid seconds value');
  END IF;
  
  v_month_start := date_trunc('month', now())::date;
  
  -- Check if session exists
  SELECT EXISTS(
    SELECT 1 FROM anonymous_tts_sessions WHERE session_id = p_session_id
  ) INTO v_session_exists;
  
  -- Create session if it doesn't exist
  IF NOT v_session_exists THEN
    INSERT INTO anonymous_tts_sessions (
      session_id, 
      user_agent,
      total_tts_seconds,
      total_full_cast_seconds
    ) VALUES (
      p_session_id,
      p_user_agent,
      CASE WHEN p_source = 'reader' THEN p_seconds ELSE 0 END,
      CASE WHEN p_source = 'full-cast' THEN p_seconds ELSE 0 END
    );
  ELSE
    -- Update session totals and last_active
    UPDATE anonymous_tts_sessions
    SET 
      last_active_at = now(),
      total_tts_seconds = total_tts_seconds + CASE WHEN p_source = 'reader' THEN p_seconds ELSE 0 END,
      total_full_cast_seconds = total_full_cast_seconds + CASE WHEN p_source = 'full-cast' THEN p_seconds ELSE 0 END
    WHERE session_id = p_session_id;
  END IF;
  
  -- Upsert monthly usage by source
  INSERT INTO anonymous_tts_usage (
    session_id,
    month_start,
    source,
    used_seconds
  ) VALUES (
    p_session_id,
    v_month_start,
    COALESCE(NULLIF(p_source, ''), 'reader'),
    p_seconds
  )
  ON CONFLICT (session_id, month_start, source)
  DO UPDATE SET 
    used_seconds = anonymous_tts_usage.used_seconds + EXCLUDED.used_seconds,
    updated_at = now();
  
  -- Get current total for this session
  SELECT COALESCE(SUM(used_seconds), 0)
  INTO v_total_seconds
  FROM anonymous_tts_usage
  WHERE session_id = p_session_id
    AND month_start = v_month_start;
  
  RETURN jsonb_build_object(
    'success', true,
    'session_id', p_session_id,
    'total_seconds_this_month', v_total_seconds,
    'total_minutes_this_month', ROUND(v_total_seconds / 60.0, 2)
  );
END;
$$;

-- RPC to convert anonymous session to user
CREATE OR REPLACE FUNCTION convert_anonymous_to_user(
  p_session_id text,
  p_user_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  v_tts_seconds integer;
  v_full_cast_seconds integer;
  v_month_start date;
BEGIN
  v_month_start := date_trunc('month', now())::date;
  
  -- Get anonymous totals
  SELECT 
    COALESCE(total_tts_seconds, 0),
    COALESCE(total_full_cast_seconds, 0)
  INTO v_tts_seconds, v_full_cast_seconds
  FROM anonymous_tts_sessions
  WHERE session_id = p_session_id;
  
  IF v_tts_seconds IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Session not found');
  END IF;
  
  -- Mark session as converted
  UPDATE anonymous_tts_sessions
  SET 
    converted_to_user_id = p_user_id,
    conversion_date = now()
  WHERE session_id = p_session_id;
  
  -- Transfer usage to authenticated user tables
  -- Only transfer current month's usage
  INSERT INTO tts_quota_monthly (user_id, month_start, used_seconds)
  VALUES (p_user_id, v_month_start, v_tts_seconds + v_full_cast_seconds)
  ON CONFLICT (user_id, month_start)
  DO UPDATE SET 
    used_seconds = tts_quota_monthly.used_seconds + EXCLUDED.used_seconds;
  
  -- Transfer by source
  IF v_tts_seconds > 0 THEN
    INSERT INTO tts_quota_monthly_by_source (user_id, month_start, source, used_seconds)
    VALUES (p_user_id, v_month_start, 'reader', v_tts_seconds)
    ON CONFLICT (user_id, month_start, source)
    DO UPDATE SET 
      used_seconds = tts_quota_monthly_by_source.used_seconds + EXCLUDED.used_seconds;
  END IF;
  
  IF v_full_cast_seconds > 0 THEN
    INSERT INTO tts_quota_monthly_by_source (user_id, month_start, source, used_seconds)
    VALUES (p_user_id, v_month_start, 'full-cast', v_full_cast_seconds)
    ON CONFLICT (user_id, month_start, source)
    DO UPDATE SET 
      used_seconds = tts_quota_monthly_by_source.used_seconds + EXCLUDED.used_seconds;
  END IF;
  
  RETURN jsonb_build_object(
    'success', true,
    'transferred_tts_seconds', v_tts_seconds,
    'transferred_full_cast_seconds', v_full_cast_seconds,
    'user_id', p_user_id
  );
END;
$$;

-- RPC to get anonymous user's current usage
CREATE OR REPLACE FUNCTION get_anonymous_usage(
  p_session_id text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_month_start date;
  v_total_seconds integer;
  v_tts_seconds integer;
  v_full_cast_seconds integer;
BEGIN
  v_month_start := date_trunc('month', now())::date;
  
  -- Get total usage for this session this month
  SELECT 
    COALESCE(SUM(used_seconds), 0)
  INTO v_total_seconds
  FROM anonymous_tts_usage
  WHERE session_id = p_session_id
    AND month_start = v_month_start;
  
  -- Get breakdown by source
  SELECT 
    COALESCE(SUM(CASE WHEN source = 'reader' THEN used_seconds ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN source = 'full-cast' THEN used_seconds ELSE 0 END), 0)
  INTO v_tts_seconds, v_full_cast_seconds
  FROM anonymous_tts_usage
  WHERE session_id = p_session_id
    AND month_start = v_month_start;
  
  RETURN jsonb_build_object(
    'session_id', p_session_id,
    'total_seconds', v_total_seconds,
    'total_minutes', ROUND(v_total_seconds / 60.0, 2),
    'tts_seconds', v_tts_seconds,
    'full_cast_seconds', v_full_cast_seconds,
    'month_start', v_month_start
  );
END;
$$;

-- === SUBSCRIPTION SYSTEM ===

-- Create profiles table if it doesn't exist (Supabase may auto-create)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  subscription_id UUID,
  customer_id TEXT, -- Payment gateway customer ID (e.g., Stripe customer ID)
  tts_minutes_limit INTEGER DEFAULT 0,
  tts_minutes_used INTEGER DEFAULT 0, -- Total usage (subscription + prepaid) in seconds
  subscription_minutes_used INTEGER DEFAULT 0, -- Subscription usage only in seconds
  last_reset_date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- RLS policies for profiles
CREATE POLICY "Users can read own profile" ON profiles
  FOR SELECT USING (id = auth.uid());

CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (id = auth.uid());

CREATE POLICY "Users can insert own profile" ON profiles
  FOR INSERT WITH CHECK (id = auth.uid());

-- Indexes for profiles
CREATE INDEX IF NOT EXISTS idx_profiles_subscription_id ON profiles(subscription_id) WHERE subscription_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON profiles(id);
CREATE INDEX IF NOT EXISTS idx_profiles_customer_id ON profiles(customer_id) WHERE customer_id IS NOT NULL;

-- Add updated_at trigger for profiles
DROP TRIGGER IF EXISTS trg_profiles_updated_at ON profiles;
CREATE TRIGGER trg_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Create subscriptions table
CREATE TABLE IF NOT EXISTS subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('active', 'inactive', 'trial', 'cancelled', 'past_due')),
  plan_id TEXT,
  current_period_start TIMESTAMP WITH TIME ZONE,
  current_period_end TIMESTAMP WITH TIME ZONE,
  cancel_at_period_end BOOLEAN DEFAULT FALSE,
  payment_gateway_subscription_id TEXT UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on subscriptions
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- RLS policies for subscriptions
CREATE POLICY "Users can read own subscriptions" ON subscriptions
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Service role can manage subscriptions" ON subscriptions
  FOR ALL USING (auth.role() = 'service_role');

-- Indexes for subscriptions
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_gateway_id ON subscriptions(payment_gateway_subscription_id) WHERE payment_gateway_subscription_id IS NOT NULL;

-- Add updated_at trigger for subscriptions
DROP TRIGGER IF EXISTS trg_subscriptions_updated_at ON subscriptions;
CREATE TRIGGER trg_subscriptions_updated_at
  BEFORE UPDATE ON subscriptions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Create products table
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gateway_product_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  tts_minutes_included INTEGER NOT NULL DEFAULT 0,
  price_per_month INTEGER,
  currency TEXT DEFAULT 'usd',
  is_active BOOLEAN DEFAULT TRUE,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on products
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- RLS policies for products (public read, admin write)
CREATE POLICY "Anyone can read active products" ON products
  FOR SELECT USING (is_active = TRUE OR auth.role() = 'service_role');

CREATE POLICY "Service role can manage products" ON products
  FOR ALL USING (auth.role() = 'service_role');

-- Indexes for products
CREATE INDEX IF NOT EXISTS idx_products_gateway_id ON products(gateway_product_id);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON products(is_active);

-- Add updated_at trigger for products
DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Create prices table
CREATE TABLE IF NOT EXISTS prices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  gateway_price_id TEXT UNIQUE NOT NULL,
  unit_amount INTEGER NOT NULL,
  currency TEXT DEFAULT 'usd',
  interval TEXT NOT NULL CHECK (interval IN ('month', 'year')),
  interval_count INTEGER DEFAULT 1,
  is_active BOOLEAN DEFAULT TRUE,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on prices
ALTER TABLE prices ENABLE ROW LEVEL SECURITY;

-- RLS policies for prices
CREATE POLICY "Anyone can read active prices" ON prices
  FOR SELECT USING (is_active = TRUE OR auth.role() = 'service_role');

CREATE POLICY "Service role can manage prices" ON prices
  FOR ALL USING (auth.role() = 'service_role');

-- Indexes for prices
CREATE INDEX IF NOT EXISTS idx_prices_gateway_id ON prices(gateway_price_id);
CREATE INDEX IF NOT EXISTS idx_prices_product_id ON prices(product_id);
CREATE INDEX IF NOT EXISTS idx_prices_is_active ON prices(is_active);

-- Add updated_at trigger for prices
DROP TRIGGER IF EXISTS trg_prices_updated_at ON prices;
CREATE TRIGGER trg_prices_updated_at
  BEFORE UPDATE ON prices
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Add foreign key from profiles to subscriptions
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'profiles_subscription_id_fkey'
  ) THEN
    ALTER TABLE profiles 
    ADD CONSTRAINT profiles_subscription_id_fkey 
    FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL;
  END IF;
END $$;

-- RPC function to check TTS usage limit
CREATE OR REPLACE FUNCTION check_tts_usage_limit(
  p_user_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID;
  v_minutes_limit INTEGER;
  v_minutes_used INTEGER;
  v_subscription_seconds_used INTEGER;
  v_prepaid_minutes INTEGER := 0;
  v_last_reset_date TIMESTAMP WITH TIME ZONE;
  v_current_period_end TIMESTAMP WITH TIME ZONE;
  v_needs_reset BOOLEAN := FALSE;
  v_minutes_remaining INTEGER;
  v_limit_exceeded BOOLEAN := FALSE;
BEGIN
  -- Get user ID
  v_user_id := COALESCE(p_user_id, auth.uid());
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object(
      'has_limit', false,
      'error', 'User ID is required'
    );
  END IF;

  -- Fetch user's subscription and limit info (including prepaid)
  SELECT 
    p.tts_minutes_limit,
    COALESCE(p.subscription_minutes_used, 0),
    COALESCE(p.prepaid_minutes, 0),
    p.last_reset_date,
    s.current_period_end
  INTO 
    v_minutes_limit,
    v_subscription_seconds_used,
    v_prepaid_minutes,
    v_last_reset_date,
    v_current_period_end
  FROM profiles p
  LEFT JOIN subscriptions s ON s.id = p.subscription_id
  WHERE p.id = v_user_id;

  -- If profile doesn't exist, create it with default limits
  IF v_minutes_limit IS NULL THEN
    INSERT INTO profiles (id, tts_minutes_limit, tts_minutes_used, subscription_minutes_used, prepaid_minutes)
    VALUES (v_user_id, 0, 0, 0, 0)
    ON CONFLICT (id) DO NOTHING;
    
    SELECT tts_minutes_limit, COALESCE(subscription_minutes_used, 0), COALESCE(prepaid_minutes, 0), last_reset_date
    INTO v_minutes_limit, v_subscription_seconds_used, v_prepaid_minutes, v_last_reset_date
    FROM profiles
    WHERE id = v_user_id;
  END IF;

  -- Convert subscription seconds to minutes
  v_minutes_used := COALESCE(v_subscription_seconds_used, 0) / 60;

  -- Check if reset is needed based on subscription period
  IF v_current_period_end IS NOT NULL AND v_last_reset_date IS NOT NULL THEN
    IF v_last_reset_date < v_current_period_end AND NOW() >= v_current_period_end THEN
      v_needs_reset := TRUE;
    END IF;
  ELSIF v_last_reset_date IS NULL THEN
    -- First time check, set reset date
    v_needs_reset := TRUE;
  END IF;

  -- Calculate remaining minutes (include prepaid in total)
  IF v_minutes_limit > 0 THEN
    v_minutes_remaining := GREATEST(0, v_minutes_limit - v_minutes_used) + v_prepaid_minutes;
    v_limit_exceeded := (v_minutes_limit - v_minutes_used) <= 0 AND v_prepaid_minutes <= 0;
  ELSIF v_prepaid_minutes > 0 THEN
    -- No subscription limit, but has prepaid
    v_minutes_remaining := v_prepaid_minutes;
    v_limit_exceeded := FALSE;
  ELSE
    -- No limit set (unlimited or free tier)
    v_minutes_remaining := NULL;
    v_limit_exceeded := FALSE;
  END IF;

  RETURN jsonb_build_object(
    'has_limit', v_minutes_limit > 0 OR v_prepaid_minutes > 0,
    'minutes_limit', v_minutes_limit,
    'prepaid_minutes', v_prepaid_minutes,
    'subscription_minutes_used', v_minutes_used,
    'minutes_used', v_minutes_used,
    'minutes_remaining', v_minutes_remaining,
    'limit_exceeded', v_limit_exceeded,
    'needs_reset', v_needs_reset,
    'last_reset_date', v_last_reset_date,
    'current_period_end', v_current_period_end
  );
END;
$$;

-- RPC function to reset user TTS usage
CREATE OR REPLACE FUNCTION reset_user_tts_usage(
  p_user_id UUID DEFAULT NULL,
  p_reset_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID;
BEGIN
  v_user_id := COALESCE(p_user_id, auth.uid());
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'User ID is required');
  END IF;

  -- Reset subscription usage and total usage, but keep prepaid_minutes unchanged
  UPDATE profiles
  SET 
    subscription_minutes_used = 0,
    tts_minutes_used = 0,
    last_reset_date = NOW(),
    updated_at = NOW()
  WHERE id = v_user_id;

  -- If profile doesn't exist, create it
  IF NOT FOUND THEN
    INSERT INTO profiles (id, tts_minutes_limit, tts_minutes_used, subscription_minutes_used, last_reset_date)
    VALUES (v_user_id, 0, 0, 0, NOW())
    ON CONFLICT (id) DO UPDATE
    SET subscription_minutes_used = 0, tts_minutes_used = 0, last_reset_date = NOW();
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'user_id', v_user_id,
    'reset_at', NOW(),
    'reason', p_reset_reason
  );
END;
$$;

-- RPC function to get user subscription info
CREATE OR REPLACE FUNCTION get_user_subscription_info(
  p_user_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID;
  v_profile JSONB;
  v_subscription JSONB;
  v_product JSONB;
BEGIN
  v_user_id := COALESCE(p_user_id, auth.uid());
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('error', 'User ID is required');
  END IF;

  -- Get profile info
  SELECT jsonb_build_object(
    'tts_minutes_limit', p.tts_minutes_limit,
    'tts_minutes_used', p.tts_minutes_used,
    'last_reset_date', p.last_reset_date
  )
  INTO v_profile
  FROM profiles p
  WHERE p.id = v_user_id;

  -- Get subscription info
  SELECT jsonb_build_object(
    'id', s.id,
    'status', s.status,
    'plan_id', s.plan_id,
    'current_period_start', s.current_period_start,
    'current_period_end', s.current_period_end,
    'cancel_at_period_end', s.cancel_at_period_end,
    'payment_gateway_subscription_id', s.payment_gateway_subscription_id
  )
  INTO v_subscription
  FROM subscriptions s
  WHERE s.user_id = v_user_id
    AND s.status IN ('active', 'trial')
  ORDER BY s.created_at DESC
  LIMIT 1;

  -- Get product info if subscription exists
  IF v_subscription IS NOT NULL THEN
    SELECT jsonb_build_object(
      'id', p.id,
      'name', p.name,
      'description', p.description,
      'tts_minutes_included', p.tts_minutes_included,
      'price_per_month', p.price_per_month,
      'currency', p.currency
    )
    INTO v_product
    FROM subscriptions sub
    JOIN products p ON p.gateway_product_id = sub.plan_id
    WHERE sub.user_id = v_user_id
      AND sub.status IN ('active', 'trial')
    ORDER BY sub.created_at DESC
    LIMIT 1;
  END IF;

  RETURN jsonb_build_object(
    'user_id', v_user_id,
    'profile', COALESCE(v_profile, jsonb_build_object()),
    'subscription', v_subscription,
    'product', v_product
  );
END;
$$;

-- Update increment_tts_usage to check limits and update profiles
CREATE OR REPLACE FUNCTION increment_tts_usage(
  p_user_id uuid,
  p_seconds integer,
  p_source text DEFAULT NULL,
  p_event_id text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_month_start date;
  v_event_inserted boolean := false;
  v_limit_check JSONB;
  v_minutes_limit INTEGER;
  v_minutes_used INTEGER;
  v_seconds_used INTEGER;
  v_subscription_seconds_used INTEGER;
  v_prepaid_minutes INTEGER := 0;
  v_prepaid_seconds INTEGER := 0;
  v_prepaid_to_consume INTEGER := 0;
  v_subscription_to_consume INTEGER := 0;
  v_prepaid_remaining INTEGER := 0;
  v_subscription_minutes_used NUMERIC := 0;
  v_subscription_minutes_to_add NUMERIC := 0;
  v_needs_reset BOOLEAN;
  v_subscription_id UUID;
  v_has_active_subscription BOOLEAN := FALSE;
BEGIN
  -- Validate inputs
  IF p_seconds IS NULL OR p_seconds <= 0 THEN
    RETURN;
  END IF;

  v_user_id := COALESCE(p_user_id, auth.uid());
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'increment_tts_usage: user id is required';
  END IF;

  -- Check usage limits first
  v_limit_check := check_tts_usage_limit(v_user_id);
  v_minutes_limit := (v_limit_check->>'minutes_limit')::INTEGER;
  v_needs_reset := (v_limit_check->>'needs_reset')::BOOLEAN;

  -- Reset usage if needed
  IF v_needs_reset THEN
    PERFORM reset_user_tts_usage(v_user_id, 'period_reset');
    v_minutes_used := 0;
    v_seconds_used := 0;
    v_subscription_seconds_used := 0;
  END IF;

  -- Get current balances (prepaid in minutes, subscription used in seconds, total used in seconds)
  SELECT 
    COALESCE(prepaid_minutes, 0),
    COALESCE(subscription_minutes_used, 0),
    COALESCE(tts_minutes_used, 0),
    COALESCE(tts_minutes_limit, 0),
    p.subscription_id
  INTO 
    v_prepaid_minutes,
    v_subscription_seconds_used,
    v_seconds_used,
    v_minutes_limit,
    v_subscription_id
  FROM profiles p
  WHERE p.id = v_user_id;
  
  -- Defensive check: If user has active subscription but limit is 0, try to fix it
  IF v_subscription_id IS NOT NULL THEN
    -- Check if user has an active subscription
    SELECT EXISTS(
      SELECT 1 FROM subscriptions s
      WHERE s.id = v_subscription_id
        AND s.status IN ('active', 'trial')
    ) INTO v_has_active_subscription;
    
    -- If limit is 0 but user has active subscription, try to get limit from product
    IF v_minutes_limit = 0 AND v_has_active_subscription THEN
      SELECT COALESCE(p.tts_minutes_included, 0)
      INTO v_minutes_limit
      FROM subscriptions s
      JOIN products p ON p.gateway_product_id = s.plan_id
      WHERE s.id = v_subscription_id
        AND s.status IN ('active', 'trial')
      LIMIT 1;
      
      -- If we found a valid limit, update the profile
      IF v_minutes_limit > 0 THEN
        UPDATE profiles
        SET tts_minutes_limit = v_minutes_limit
        WHERE id = v_user_id;
        
        RAISE WARNING 'Fixed tts_minutes_limit for user %: was 0, now %', v_user_id, v_minutes_limit;
      ELSE
        RAISE WARNING 'User % has active subscription but tts_minutes_limit is 0 and product not found', v_user_id;
      END IF;
    END IF;
  END IF;

  -- Convert prepaid to seconds for consumption
  v_prepaid_seconds := v_prepaid_minutes * 60;

  -- Calculate consumption: use prepaid first, then subscription
  v_prepaid_to_consume := LEAST(p_seconds, v_prepaid_seconds);
  v_subscription_to_consume := GREATEST(0, p_seconds - v_prepaid_to_consume);

  -- Convert remaining prepaid back to minutes for storage (round down)
  v_prepaid_remaining := FLOOR((v_prepaid_seconds - v_prepaid_to_consume) / 60.0);

  -- Check subscription limit only if prepaid exhausted
  IF v_subscription_to_consume > 0 AND v_minutes_limit > 0 THEN
    -- Calculate subscription minutes used (from subscription_minutes_used field)
    v_subscription_minutes_used := v_subscription_seconds_used / 60.0;
    v_subscription_minutes_to_add := v_subscription_to_consume / 60.0;
    
    IF (v_subscription_minutes_used + v_subscription_minutes_to_add) > v_minutes_limit THEN
      RAISE EXCEPTION 'TTS_USAGE_LIMIT_EXCEEDED' USING 
        MESSAGE = 'TTS usage limit exceeded. Please upgrade your subscription.',
        DETAIL = format('Current subscription usage: %s minutes, Limit: %s minutes, Prepaid remaining: %s minutes', 
                       ROUND(v_subscription_minutes_used, 2), v_minutes_limit, v_prepaid_remaining);
    END IF;
  END IF;

  v_month_start := date_trunc('month', now())::date;

  -- Insert event with idempotency check (if event_id provided)
  IF p_event_id IS NOT NULL AND p_event_id != '' THEN
    BEGIN
      INSERT INTO tts_usage_events (event_id, user_id, seconds, source)
      VALUES (p_event_id, v_user_id, p_seconds, p_source)
      ON CONFLICT (event_id) DO NOTHING
      RETURNING true INTO v_event_inserted;
      
      IF NOT v_event_inserted THEN
        RETURN;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        RAISE WARNING 'Failed to insert event with id %: %', p_event_id, SQLERRM;
    END;
  ELSE
    BEGIN
      INSERT INTO tts_usage_events (user_id, seconds, source)
      VALUES (v_user_id, p_seconds, p_source);
      v_event_inserted := true;
    EXCEPTION
      WHEN OTHERS THEN
        RAISE WARNING 'Failed to insert event: %', SQLERRM;
    END;
  END IF;

  -- Upsert monthly bucket (only if event was successfully inserted or no event_id provided)
  IF v_event_inserted OR p_event_id IS NULL THEN
    INSERT INTO tts_quota_monthly (user_id, month_start, used_seconds)
    VALUES (v_user_id, v_month_start, p_seconds)
    ON CONFLICT (user_id, month_start)
    DO UPDATE SET used_seconds = tts_quota_monthly.used_seconds + EXCLUDED.used_seconds,
                  updated_at = now();
  END IF;

  -- Upsert per-source monthly bucket
  IF v_event_inserted OR p_event_id IS NULL THEN
    INSERT INTO tts_quota_monthly_by_source (user_id, month_start, source, used_seconds)
    VALUES (v_user_id, v_month_start, COALESCE(NULLIF(p_source, ''), 'unknown'), p_seconds)
    ON CONFLICT (user_id, month_start, source)
    DO UPDATE SET used_seconds = tts_quota_monthly_by_source.used_seconds + EXCLUDED.used_seconds,
                  updated_at = now();
  END IF;

  -- Update profiles table atomically with prepaid consumption and subscription tracking
  IF v_event_inserted OR p_event_id IS NULL THEN
    UPDATE profiles 
    SET 
      prepaid_minutes = v_prepaid_remaining,
      subscription_minutes_used = subscription_minutes_used + v_subscription_to_consume,  -- Only increment subscription usage
      tts_minutes_used = tts_minutes_used + p_seconds,  -- Keep total for historical tracking
      updated_at = NOW()
    WHERE id = v_user_id;
  END IF;
END;
$$;

-- Helper function to get subscription status
CREATE OR REPLACE FUNCTION get_subscription_status(p_user_id UUID DEFAULT NULL)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID;
  v_status TEXT;
BEGIN
  v_user_id := COALESCE(p_user_id, auth.uid());
  IF v_user_id IS NULL THEN
    RETURN 'no_user';
  END IF;

  SELECT status INTO v_status
  FROM subscriptions
  WHERE user_id = v_user_id
    AND status IN ('active', 'trial')
  ORDER BY created_at DESC
  LIMIT 1;

  RETURN COALESCE(v_status, 'inactive');
END;
$$;

-- Helper function to calculate usage reset date
CREATE OR REPLACE FUNCTION calculate_usage_reset_date(p_user_id UUID DEFAULT NULL)
RETURNS TIMESTAMP WITH TIME ZONE
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID;
  v_period_end TIMESTAMP WITH TIME ZONE;
BEGIN
  v_user_id := COALESCE(p_user_id, auth.uid());
  IF v_user_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT current_period_end INTO v_period_end
  FROM subscriptions
  WHERE user_id = v_user_id
    AND status IN ('active', 'trial')
  ORDER BY created_at DESC
  LIMIT 1;

  RETURN v_period_end;
END;
$$;